<?php

namespace Samu\GestionVMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterielCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielCategoryRepository extends EntityRepository
{
}
