<?php

namespace Samu\GestionVMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProblemeComRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemeComRepository extends EntityRepository
{
}
