<?php

namespace Samu\GestionVMBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProblemeVMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemeVMRepository extends EntityRepository
{
	public function getProblemes($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('p')
		  ->leftJoin('p.commentaires', 'c')
		  ->addSelect('c')
		  ->orderBy('p.dateDebut', 'DESC')
		  ->getQuery()
		;

		$query
		  ->setFirstResult(($page-1) * $nbPerPage)
		  ->setMaxResults($nbPerPage)
		;

		return new Paginator($query, true);
	}
}
